### ISSUE TITLE
How to set different message when the jenkins build is success or failed?

### ISSUE THREAD

**Issue by fauzanazhiman** [chiragnaik/google-chat-notification-jenkins-plugin#3]

**Comment by chiragnaik** [comment]
Currently, Google chat does not support color coding. You can specify build status in your message. 
For e.g. 
<Custom message> ${JOB_NAME} ${BUILD_DISPLAY_NAME} >> *${BUILD_STATUS}*\nFor full details click on link: ${BUILD_URL}
Here,
BUILD_DISPLAY_NAME - It will be replaced by full name of your Jenkins job.
BUILD_STATUS - It will be replaced by status of your current build.
BUILD_URL - It will be replaced by full URL to your Jenkins job.

This plugin supports all pre defined Jenkins job of token macro plugin.

**Comment by fauzanazhiman** [comment]
Ok, thank you.

**Comment by vskarda** [comment]
But it does support widgets
https://developers.google.com/chat/api/guides/message-formats/cards

Any chance of implementing this to add color option to Jenkinsfile?
Thank you.
